Sprint 3
laksan1/middle.messenger.praktikum.yandex pull request #4
Opened 2023-03-19 09:09 UTC by laksan1

2023-03-19 11:42 UTC, podlovchenko requested changes
Привет) Спасибо за проделанную работу, есть несколько замечаний
1. Есть ошибки типизации `tsc --noEmit`
2. При нажатии на кнопки в приложении  страницы не открывается, например, при нажатии на "Изменить данные" `Cannot GET /settings-edit`
3. При обновлении страницы `Cannot GET /messenger`
4. На нетлифае старая версия
5. Было бы отлично очищать поле ввода после отправки сообщения
6. После того как выходишь с аккаунта все равно открывается страница профиля, должна открываться страница входа

2023-03-19 11:42 UTC, podlovchenko commented on package.json
> +		"@types/node": "^18.15.3",
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2023-03-19 11:42 UTC, podlovchenko commented on src/api/AuthAPI.ts
> +import BaseAPI from '../utils/BaseAPI'
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2023-03-19 11:42 UTC, podlovchenko commented on src/api/UserAPI.ts
> +	updateAvatar(data: UserAvatar): Promise<User> {
Здорово, что добавлена типизация для данных и ответа 👍

2023-03-19 11:42 UTC, podlovchenko commented on src/blocks/chat-add-new-chat-block/chat-add-new-chat-block.module.scss
> +	padding: 50px 30px 30px 30px;
```suggestion
	padding: 50px 30px 30px;
```

2023-03-19 11:42 UTC, podlovchenko commented on src/blocks/chat-add-new-chat-block/chat-add-new-chat-block.ts
> +import { Input } from '../../components/input/input'
Стоит придерживаться одного стиля написания
Поддержать код стайл может помочь https://prettier.io/docs/en/install.html

2023-03-19 11:42 UTC, podlovchenko commented on src/blocks/settings-block/settings-block.ts
> +						child.setProps({ src: 'https://ya-praktikum.tech/api/v2/resources/' + String(dataItem) });
Урл стоит вынести в конфиг

2023-03-19 11:42 UTC, podlovchenko commented on src/components/chat/chat-new-chat/chat-new-chat-button.ts
> +		//this.element?.addEventListener('click', this.addChat.bind(this))
Закомментированный код не стоит оставлять в проекте

2023-03-20 15:55 UTC, podlovchenko commented
Привет, спасибо за оперативные правки, в целом все ок, не хватает возможности изменять аватар

2023-03-20 16:04 UTC, laksan1 commented
![image](https://user-images.githubusercontent.com/53944188/226399441-99025a66-55df-47a7-b44c-3856bd9e5b8f.png)
Спасибо за ревью. Возможность есть, но там не совсем понятно. Аватар можно нажать, если на контур навести картинки, а не на центр. Исправляю

2023-03-21 08:22 UTC, podlovchenko commented
Работу принимаю)

2023-03-21 09:05 UTC, merged

2023-03-21 09:07 UTC, laksan1 commented
Спасибо)